### ISSUE TITLE
How to parse a 64bit integer?

### ISSUE THREAD

**Issue by krlicmuhamed** [keichi/binary-parser#26]
I have a 64bit integer I need to parse. How am I going to do this?

``` javascript
var buf = new Buffer('00000b1a2a5585c3', 'hex'); // big endian
```

**Comment by donno** [comment]
I too was wondering this a while ago when I discovered its not possible out-of-box.

The reason for this is  JavaScript itself does not support 64-bit integers.
All numbers are typically stored as a 64-bit floating point number, with the eception of the array types i.e Int32Array but there is no Int64Array.

References: http://www.2ality.com/2012/07/large-integers.html

I haven't got around to trying it but I suspect you could make parser such that you get the upper 32-bits as one integer and lower 32-bit as another so you would end up being able to go .hi and .low. You then have the problem of doing arithmetic on it.

**Comment by oparisy** [comment]
Since there is no native support for representing those, one may consider depending on an external module. [https://www.npmjs.com/package/node-int64](`node-64`) and [https://www.npmjs.com/package/long](`long`) seem to be the more popular, and do not add extra dependencies beyond themselves.

**Comment by shamansir** [comment]
There is [an implementation|https://github.com/substack/node-binary/blob/master/index.js#L371] in [node-binary package|https://github.com/substack/node-binary#bword8163264lbeuskey], though it just sums up bits in accumulator, so probably it leaves 32bit overflow to the JS engine.

**Comment by Simran-B** [comment]
`dissolve` comes with "Fast approximation of [u]int64 numbers in signed and unsigned variants":

https://github.com/deoxxa/dissolve/blob/b178eccee8ddf07c4bc40b35365314a59d61ffb0/index.js#L190

What it means is probably that you lose precision beyond 2<sup>53</sup>-1 (not 2<sup>32</sup>, bitwise operations aside).

Based on the description of `node-64`, it only carries around 64bit integers without precision loss, which means you could use `.buffer()` to simply preserve it without extra modules. Endianess can be changed by reversing the buffer in a formatter function:

```js
var parser = new Parser()
parser.buffer("int64",{ length: 8, clone:true, formatter: function(buf){ return buf.reverse() }})
parser.parse(Buffer.from("1122334455667788", "hex")) // <Buffer 88 77 66 55 44 33 22 11>
```

Comparisons are possible with buffer1.equals(buffer2), but you need to make sure that you only compare the same source types (integers, both signed or unsigned and matching endianess).

Long.js supports int64 math, but it could be a bit tricky to integrate (any dependency actually), because of the code generation and evaluation.

**Comment by cmdcolin** [comment]
We have a fork of this package  which bundles Long.js and makes it available in the eval statements so you can use it in a formatter. See https://github.com/GMOD/binary-parser https://www.npmjs.com/package/@gmod/binary-parser


So for example


    .buffer('mylong64bitint', { length: 8, formatter: function(buf) { return Long.fromBytes(buf, true, this.endian==='le').toNumber() } })

Kind of tedious but works

**Comment by Toxicable** [comment]
nodejs supports 64 ints now with BigInt https://nodejs.org/api/buffer.html#buffer_buf_readbigint64be_offset
