### ISSUE TITLE
TypeScript Definitions

### ISSUE THREAD

**Issue by 20zinnm** [keichi/binary-parser#38]
It's be amazing if we could get some TypeScript definitions. I can make them if needed.

**Comment by dolanmiu** [comment]
im making one now as my project is in Typescript. Will share once done

**Comment by sembaye** [comment]
Already done??

**Comment by riggs** [comment]
Feel free to use mine (for both binary-parser and https://github.com/feross/buffer): https://github.com/riggs/WebUSB-HID/tree/3b240c3144a9a8efdbeb3a96696bfd00e2d152b8/typings

Note the link is to an actual commit, because I'm moving away from using this library due to [bugs](https://github.com/keichi/binary-parser/issues/56) and needing both packing & parsing.

**Comment by sembaye** [comment]
Thanks riggs.

**Comment by dolanmiu** [comment]
Crap, sorry, I forgot to do it lol (year later 😂 )

**Comment by dolanmiu** [comment]
@riggs Could I ask why this type definition isn't on DefinitelyTyped? Even though it says it here:

https://github.com/riggs/WebUSB-HID/blob/3b240c3144a9a8efdbeb3a96696bfd00e2d152b8/typings/binary_parser.d.ts#L4

If this is meant to be on DefinitelyTyped, would you mind if I add it in?

**Comment by riggs** [comment]
I got side-tracked and didn't get around to throwing them in their own repo & all that.

Feel free to add them.

**Comment by dolanmiu** [comment]
Merged!

Feel free to type this for convenience:

```
$ npm install @types/binary-parser --save
```

**Comment by keichi** [comment]
Closing this issue now. Thanks for the help @riggs and @dolanmiu.
